### ISSUE TITLE
Pre-computed maps of ResNet-50 and NC4K

### ISSUE THREAD

**Issue by CRRCOO** [thograce/C2FNet#5]
Hello, I notice that the repo does not contain the prediction maps of C2FNet (ResNet-50). Could you please provide the prediction maps of C2FNet with ResNet-50 backbone? And could you kindly provide the prediction maps of NC4K dataset for both ResNet-50 and Res2Net-50 backbones? Thank you so much!

**Comment by thograce** [comment]
> Hello, I notice that the repo does not contain the prediction maps of C2FNet (ResNet-50). Could you please provide the prediction maps of C2FNet with ResNet-50 backbone? And could you kindly provide the prediction maps of NC4K dataset for both ResNet-50 and Res2Net-50 backbones? Thank you so much!

The [download link](https://drive.google.com/file/d/1l_qaEOWNaZVyEu7rk9K_C9Pcuicay0uk/view?usp=share_link)  in README contains NC4K (Res2Net).
The prediction maps of C2FNet (ResNet-50) cannot be provided in a short time because I have no access to the experimental environment. If you are in a hurry, you can send your WeChat to my email (thograce@163.com). Let's discuss it on WeChat.

**Comment by CRRCOO** [comment]
> The [download link](https://drive.google.com/file/d/1l_qaEOWNaZVyEu7rk9K_C9Pcuicay0uk/view?usp=share_link) in README contains NC4K (Res2Net). The prediction maps of C2FNet (ResNet-50) cannot be provided in a short time because I have no access to the experimental environment. If you are in a hurry, you can send your WeChat to my email ([thograce@163.com](mailto:thograce@163.com)). Let's discuss it on WeChat.

OK, thank you very much!
